#!/bin/bash

STORAGE=$PW_PATH/pw.txt
touch -- "$STORAGE"

COL_SP=":::::"

help() {
	echo -e "\nAvailable commands:\n"
	echo -e "  list              - Show all keys"
	echo -e "  add <key> <value> - Add a key/value pair"
	echo -e "  del <key>         - Remove a key"
	echo -e "  get <key>         - Copy value to clipboard"
	echo -e "  ssh <key>         - Copy value and run ssh"
	echo
	exit
}

err () {
	echo $1
	exit
}

invalid () {
	err "Command '$1' does not exist"
}

list () {
	cat $STORAGE | awk -F $COL_SP '{print $1}'
}

copy () {
	if [ "$(uname)" == "Darwin" ]; then
		echo $1 | tr -d '\n' | pbcopy
	elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
		echo $1 | tr -d '\n' | xclip -selection c
	# elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]; then
	    # Do something under 32 bits Windows NT platform
	# elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW64_NT" ]; then
	    # Do something under 64 bits Windows NT platform
	fi
}

get () {
	if [ -z $2 ] ; then
		err "Please enter a key"
	fi

	PASSWORD=$(awk -F $COL_SP '/^'$2$COL_SP'/{print $2}' $STORAGE)

	if [ -z $PASSWORD ] ; then
		err "Key '$2' does not exist"
	fi

	if [[ $(awk -F $COL_SP '/^'$2'/{print $3}' $STORAGE) -eq 1 ]] ; then
		PASSWORD=$(echo $PASSWORD | openssl aes-256-cbc -a -A -d)
	fi

	copy $PASSWORD
}

del () {
	sed -E "/^$2$COL_SP.*$/d" $STORAGE > $STORAGE.bak && mv $STORAGE.bak $STORAGE
}

add () {
	if grep -q '^'$2 $STORAGE ; then
		err "Key '$2' already exists"
	fi

	if [[ -z $2 || -z $3 ]] ; then
		err "Please enter a key and a value"
	fi

	LOGIN=$2

	if [[ -z $4 ]] ; then
		PASSWORD=$3
		ENCRYPT=0
	else
		PASSWORD=$(echo $3 | openssl aes-256-cbc -a -A)
		ENCRYPT=1
	fi

	printf "%s${COL_SP}%s${COL_SP}%s\n" $LOGIN $PASSWORD $ENCRYPT >> $STORAGE
}

cssh () {
	get $@
	ssh $2
}

if [ -z "$1" ] ; then
	help
fi

case $1 in
	help) help ;;
	list) list ;;
	get)  get $@ ;;
	add)  add $@ ;;
	del)  del $@ ;;
	ssh)  cssh $@ ;;
	*)    invalid $@ ;;
esac
